//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.27 at 01:57:39 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.han.nl/schemas/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.han.ica.daretwodate;
